export const mockDashboardData = {
  totalUsers: 1200,
  activeSessions: 350,
  salesRevenue: 45000,
  salesData: [
    { month: "Jan", sales: 4000 },
    { month: "Feb", sales: 3000 },
    { month: "Mar", sales: 5000 },
    { month: "Apr", sales: 6000 },
    { month: "May", sales: 2000 },
    { month: "Jun", sales: 1500 },
    { month: "Jul", sales: 4700 },
    { month: "Aug", sales: 3200 },
    { month: "Sep", sales: 8000 },
    { month: "Oct", sales: 7500 },
    { month: "Nov", sales: 7000 },
    { month: "Dec", sales: 9500 },
  ],
  userGrowth: [
    { month: "Jan", users: 180 },
    { month: "Feb", users: 190 },
    { month: "Mar", users: 220 },
    { month: "Apr", users: 240 },
    { month: "May", users: 180 },
    { month: "Jun", users: 150 },
    { month: "Jul", users: 170 },
    { month: "Aug", users: 185 },
    { month: "Sep", users: 165 },
    { month: "Oct", users: 190 },
    { month: "Nov", users: 215 },
    { month: "Dec", users: 245 },
  ],
  categoryDist: [
    { name: "Electronics", value: 40 },
    { name: "Clothing", value: 30 },
    { name: "Books", value: 20 },
    { name: "Other", value: 10 },
  ],
  tableData: [
    { id: 1, name: "John Doe", email: "john@example.com", sales: 1500 },
    { id: 2, name: "Jane Smith", email: "jane@example.com", sales: 2000 },
  ],
};